

const firebaseConfig = {
  apiKey: "PASTE_YOUR_FIREBASE_API_KEY_HERE",
  authDomain: "PASTE_YOUR_AUTH_DOMAIN_HERE",
  projectId: "PASTE_YOUR_PROJECT_ID_HERE",
  storageBucket: "PASTE_YOUR_STORAGE_BUCKET_HERE",
  messagingSenderId: "PASTE_YOUR_SENDER_ID_HERE",
  appId: "PASTE_YOUR_APP_ID_HERE",
  databaseURL: "PASTE_YOUR_DATABASE_URL_HERE"
};

const GOOGLE_MAPS_API_KEY = "PASTE_YOUR_GOOGLE_MAPS_KEY_HERE";

const GOOGLE_MAPS_MAP_ID = "PASTE_YOUR_GOOGLE_MAP_ID_HERE";